
// This file was auto-generated by ML.NET Model Builder. 

using TitanicModel_mbconfig_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
TitanicModel_mbconfig.ModelInput sampleData = new TitanicModel_mbconfig.ModelInput()
{
    Pclass = 3F,
    Sex = @"female",
    Age = @"26",
    SibSp = 0F,
    Parch = 0F,
    Fare = @"7.925",
    Embarked = @"S",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Survived with predicted Survived from sample data...\n\n");


Console.WriteLine($"Survived: {1F}");
Console.WriteLine($"Pclass: {3F}");
Console.WriteLine($"Sex: {@"female"}");
Console.WriteLine($"Age: {@"26"}");
Console.WriteLine($"SibSp: {0F}");
Console.WriteLine($"Parch: {0F}");
Console.WriteLine($"Fare: {@"7.925"}");
Console.WriteLine($"Embarked: {@"S"}");


var sortedScoresWithLabel = TitanicModel_mbconfig.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

